# frozen_string_literal: true

##
# Comprehensive documentation generator.
# Generates all documentation including README from model features, interactions, and tests.
class ComprehensiveDocsGenerator
  def initialize
    Rails.application.eager_load! if defined?(Rails)
  end

  def generate_all
    puts "📚 Generating comprehensive documentation..."
    puts "=" * 80

    generate_readme
    generate_model_features_doc
    generate_interactions_doc
    generate_capabilities_doc
    generate_architecture_doc
    generate_api_index
    generate_testing_ux_doc
    generate_vitepress_config

    puts "\n✅ All documentation generated successfully!"
  end

  def generate_testing_ux_doc
    puts "\n📝 Generating Testing UX documentation..."

    # Delegate to DocsGenerator for consistency
    begin
      docs_generator_path = Rails.root.join("lib", "tasks", "docs_generator.rb")
      if File.exist?(docs_generator_path)
        require docs_generator_path.to_s
        generator = DocsGenerator.new
        generator.send(:generate_testing_ux_doc)
        puts "  ✅ docs/testing-ux.md"
      else
        puts "  ⚠️  DocsGenerator not found, skipping Testing UX doc"
      end
    rescue LoadError, StandardError => e
      puts "  ⚠️  Testing UX doc generation failed: #{e.message}"
    end
  end

  def generate_vitepress_config
    puts "\n⚙️  Generating VitePress config..."

    # Use the existing DocsGenerator to generate VitePress config
    # This requires discovering components first
    begin
      docs_generator_path = Rails.root.join("lib", "tasks", "docs_generator.rb")
      if File.exist?(docs_generator_path)
        require docs_generator_path.to_s
        generator = DocsGenerator.new
        # Discover components and examples needed for config generation
        generator.send(:discover_components)
        generator.send(:extract_test_examples)
        generator.generate_vitepress_config

        # Verify auto-generated header was added
        config_path = Rails.root.join("docs", ".vitepress", "config.js")
        if File.exist?(config_path)
          content = File.read(config_path)
          unless content.include?("Auto-generated")
            # Add header if missing (shouldn't happen, but safety check)
            content = "// Auto-generated VitePress configuration\n" \
                     "// To regenerate: rake docs:generate_all or rake docs:from_tests\n" \
                     "// Last updated: #{Time.current.strftime("%Y-%m-%d %H:%M:%S")}\n" \
                     "//\n" \
                     "// This file is automatically generated from Rails components.\n" \
                     "// Do not edit manually - changes will be overwritten.\n\n" + content
            File.write(config_path, content)
          end
        end

        puts "  ✅ docs/.vitepress/config.js (auto-generated)"
      else
        puts "  ⚠️  DocsGenerator not found, skipping VitePress config"
      end
    rescue LoadError, StandardError => e
      puts "  ⚠️  VitePress config generation failed: #{e.message}"
      puts "     Run 'rake docs:from_tests' to generate VitePress config"
    end
  end

  def generate_readme
    puts "\n📝 Generating README.md..."

    content = +"# OpenRemote Rails\n\n"
    content << "Rails application mirroring OpenRemote Java manager functionality.\n\n"
    content << "> **Note**: This README is auto-generated from model features, interactions, and tests.\n"
    content << "> To regenerate: `rake docs:generate_all`\n\n"
    content << <<~MARKDOWN

      ## Features

      This application provides comprehensive asset management, rule execution, data analytics, and user management capabilities.

      ### Core Capabilities

      #{generate_core_capabilities}

      ### Model Interactions

      Models interact with each other through shared concerns:

      #{generate_interactions_summary}

      ## Quick Start

      ### Installation

      ```bash
      bundle install
      rails db:create db:migrate db:seed
      ```

      ### Running the Application

      ```bash
      # Development server
      rails server

      # RailsAdmin interface (mounted at /api)
      # Requires authentication and appropriate role
      ```

      ### Testing

      ```bash
      # Run all tests
      bundle exec rspec

      # Run with coverage
      COVERAGE=true bundle exec rspec

      # Run CI checks
      bin/ci
      ```

      ## Architecture

      ### Models

      #{generate_models_summary}

      ### Concerns

      Concerns enable model interactions and shared behaviors:

      #{generate_concerns_summary}

      ## Documentation

      All documentation is compiled in `docs/` and built by VitePress to `public/docs/`.

      - **[Model Features](docs/model_features.md)** - Features declared by each model
      - **[Model Interactions](docs/model_interactions.md)** - How models interact via concerns
      - **[Capabilities](docs/capabilities.md)** - Full application capabilities from tests
      - **[Architecture](docs/architecture.md)** - System architecture overview
      - **[API Documentation](docs/api/)** - API reference documentation

      **Documentation Workflow:**
      1. All docs are compiled together in `docs/`
      2. VitePress builds from `docs/` to `public/docs/`
      3. Documentation is accessible at `/docs/` in production

      **Viewing Documentation:**
      - **Development**: `npm run docs:dev` (serves from `docs/`)
      - **Production**: Built to `public/docs/` (accessible at `/docs/`)
      - **GitHub Pages**: Automatically deployed from `docs/`

      ## Generating Documentation

      All documentation is **auto-generated** from model features, interactions, and tests.

      ```bash
      # Generate all documentation (including README)
      rake docs:generate_all

      # Generate specific docs
      rake docs:readme
      rake docs:features
      rake docs:interactions
      rake docs:capabilities
      ```

      > **Note**: Documentation auto-generates after running tests if `GENERATE_DOCS != "false"`

      ## Authentication

      The application implements Devise-like authentication features:

      - **Email Confirmation**: Users must confirm their email before logging in
      - **Password Reset**: Users can reset passwords via email (6-hour expiration)
      - **Remember Me**: Users can stay logged in for 2 weeks
      - **Account Locking**: Accounts lock after 5 failed login attempts (2-hour lock)

      ### Default Admin User (Development/Test Only)

      - **Email**: Configurable via `SUPER_ADMIN_EMAIL` environment variable (default: `admin@openremote.local`)
      - **Password**: Randomly generated secure password (16 characters)

      ⚠️ **Security**: Default credentials are only created in development and test environments.

      ## Role-Based Access Control

      Uses Rolify for role management:

      - **Admin**: Full access to everything, including user/role management
      - **Manager**: Can manage assets, rules, data points, notifications; read-only for users
      - **Viewer**: Read-only access to assets, rules, and data
      - **Guest**: No access (default for unauthenticated users)

      ## RailsAdmin

      RailsAdmin is mounted at `/api` and serves as the primary API interface.

      Access requires:
      1. User authentication (login)
      2. Admin role or appropriate permissions

      ## Database Migrations

      ```bash
      # Run migrations
      bundle exec rails db:migrate

      # Reset database (development/test)
      bundle exec rails db:reset
      ```

      ## Code Quality

      ```bash
      # Run RuboCop
      bundle exec rubocop

      # Auto-fix RuboCop offenses
      bundle exec rubocop -A

      # Run Brakeman security scan
      bundle exec brakeman

      # Run bundler-audit
      bundle exec bundler-audit
      ```

      ## License

      [Add your license here]

      ## Contributing

      [Add contributing guidelines here]

      ---

      **Last Updated**: #{Time.current.strftime("%Y-%m-%d %H:%M:%S")} (Auto-generated)
    MARKDOWN

    File.write("README.md", content)
    puts "  ✅ README.md"
  end

  def generate_model_features_doc
    puts "\n📋 Generating model features documentation..."

    content = +"# Model Features\n\n"
    content << "> **Auto-generated** from model feature declarations.\n"
    content << "> To regenerate: `rake docs:features`\n\n"
    content << "This document describes features declared by each model.\n\n"
    content << "**Last Updated**: #{Time.current.strftime("%Y-%m-%d %H:%M:%S")}\n\n"
    content << "---\n\n"

    models = ActiveRecord::Base.descendants.select { |m| m.respond_to?(:features) && m.features.any? }

    models.each do |model|
      content << model.feature_documentation
      content << "\n---\n\n"
    end

    File.write("docs/model_features.md", content)
    puts "  ✅ docs/model_features.md"
  end

  def generate_interactions_doc
    puts "\n🔗 Generating interactions documentation..."

    content = +"# Model Interactions via Concerns\n\n"
    content << "> **Auto-generated** from concern interaction declarations.\n"
    content << "> To regenerate: `rake docs:interactions`\n\n"
    content << "This document describes how models interact with each other through shared concerns.\n\n"
    content << "**Last Updated**: #{Time.current.strftime("%Y-%m-%d %H:%M:%S")}\n\n"
    content << "---\n\n"

    concerns = find_concerns_with_interactions

    concerns.each do |concern|
      content << "## #{concern.name}\n\n"
      content << "This concern enables the following model interactions:\n\n"

      concern.enables_interactions.each do |interaction|
        models = interaction[:models].map { |m| "`#{m}`" }.join(", ")
        content << "### #{interaction[:type].to_s.humanize}\n\n"
        content << "- **Models**: #{models}\n"
        content << "- **Description**: #{interaction[:description]}\n\n" if interaction[:description]
      end

      content << "---\n\n"
    end

    # Model capabilities section
    content << "## Model Capabilities\n\n"

    models_with_concerns = ActiveRecord::Base.descendants.select do |model|
      model.included_modules.any? { |mod| mod.respond_to?(:enables_interactions) }
    end

    models_with_concerns.each do |model|
      content << "### #{model.name}\n\n"
      content << "**Interactions enabled by concerns:**\n\n"

      model.included_modules.select { |mod| mod.respond_to?(:enables_interactions) }.each do |concern|
        concern.enables_interactions.each do |interaction|
          if interaction[:models].include?(model.name.to_sym)
            content << "- **#{interaction[:type].to_s.humanize}**: #{interaction[:description]}\n"
          end
        end
      end

      content << "\n"
    end

    File.write("docs/model_interactions.md", content)
    puts "  ✅ docs/model_interactions.md"
  end

  def generate_capabilities_doc
    puts "\n💡 Generating capabilities documentation..."

    if File.exist?("lib/tasks/capability_extractor.rb")
      require_relative "capability_extractor"
      extractor = CapabilityExtractor.new(
        spec_dir: "spec/features",
        output_file: "docs/capabilities.md"
      )
      extractor.save
      puts "  ✅ docs/capabilities.md"
    else
      puts "  ⚠️  Capability extractor not found, skipping..."
    end
  end

  def generate_architecture_doc
    puts "\n🏗️  Generating architecture documentation..."

    content = +"# Architecture Overview\n\n"
    content << "> **Auto-generated** from code structure and feature declarations.\n"
    content << "> To regenerate: `rake docs:architecture`\n\n"
    content << <<~MARKDOWN
      # Architecture Overview

      ## System Architecture

      This application follows a modular architecture where models interact through shared concerns.

      ### Core Principles

      1. **Models declare features** - Each model explicitly declares its capabilities
      2. **Concerns enable interactions** - Models interact through shared concerns, not direct dependencies
      3. **Test-driven documentation** - Tests serve as executable documentation
      4. **Feature-driven development** - Features are declared first, then implemented

      ## Model Layer

      ### Core Models

      #{generate_models_list}

      ### Model Features

      Models declare their features using the `feature` method:

      ```ruby
      class Asset < ApplicationRecord
        include TestExpectations

        feature :validates, :name, presence: true
        feature :associates, :belongs_to, :asset_type
        feature :provides, :from_openremote_json, :to_openremote_json_tree
        feature :scopes, :solar_arrays, :solar_parks
      end
      ```

      ## Concern Layer

      Concerns provide shared behaviors and enable model interactions:

      #{generate_concerns_list}

      ### Interaction Patterns

      Concerns declare interactions using `enables_interaction`:

      ```ruby
      module Mapping::JsonImport
        extend ConcernFeatures

        enables_interaction :json_import, [:Asset],#{' '}
          "Enables Asset to import from OpenRemote JSON format"
      end
      ```

      ## Data Flow

      ### Asset Management Flow

      1. **Import**: Asset imports from OpenRemote JSON via `Mapping::JsonImport`
      2. **Query**: Asset queries data via `Assets::Querying`
      3. **Analyze**: DataPoint performs analytics via `DataPoint::Analytics`
      4. **Export**: Asset exports to OpenRemote JSON via `Mapping::JsonExport`

      ### Rule Execution Flow

      1. **Schedule**: Rule scheduled via `RuleManager`
      2. **Execute**: Rule executes against Asset conditions via `Rule::Execution`
      3. **Notify**: Rule triggers Notification creation
      4. **Track**: RuleExecution records execution history

      ## Testing Architecture

      ### Test Structure

      - **Feature Specs** (`spec/features/`) - High-level capabilities and workflows
      - **Model Specs** (`spec/models/`) - Unit tests for models
      - **Concern Specs** (`spec/models/concerns/`) - Tests for shared behaviors
      - **Shared Examples** (`spec/support/shared_examples/`) - Reusable test patterns

      ### Test Generation

      Tests can be generated from feature declarations:

      ```bash
      rake features:generate_tests
      ```

      ## Documentation Architecture

      All documentation is auto-generated from:

      1. **Model feature declarations** - What models can do
      2. **Concern interaction declarations** - How models interact
      3. **Test examples** - Executable documentation
      4. **Code structure** - Architecture patterns

      Generate all documentation:

      ```bash
      rake docs:generate_all
      ```

      **Last Updated**: #{Time.current.strftime("%Y-%m-%d %H:%M:%S")}
    MARKDOWN

    File.write("docs/architecture.md", content)
    puts "  ✅ docs/architecture.md"
  end

  def generate_api_index
    puts "\n📖 Generating API index..."

    content = +"# API Documentation Index\n\n"
    content << "> **Auto-generated** from code structure.\n"
    content << "> To regenerate: `rake docs:api_index`\n\n"
    content << "# API Documentation Index\n\n"

    # Discover actual files in docs/api
    api_dir = Rails.root.join("docs", "api")
    return unless File.exist?(api_dir)

    # Compute file types dynamically from actual files
    files_by_type = Hash.new { |h, k| h[k] = [] }

    # Find all markdown files
    Dir.glob(api_dir.join("**", "*.md")).each do |file_path|
      relative_path = file_path.sub(api_dir.to_s + "/", "")
      next if relative_path == "index.md" # Skip index.md itself

      relative_link = "./#{relative_path}"
      type, name = categorize_file(relative_path)

      files_by_type[type] << { name: name, link: relative_link } if type && name
    end

    # Generate sections for all discovered types (computed, not hardcoded)
    files_by_type.keys.sort.each do |type|
      files = files_by_type[type].sort_by { |f| f[:name] }
      next if files.empty?

      content << "## #{type.to_s.capitalize}\n\n"
      files.each do |file|
        content << "- [#{file[:name]}](#{file[:link]})\n"
      end
      content << "\n"
    end

    FileUtils.mkdir_p("docs/api")
    File.write("docs/api/index.md", content)
    puts "  ✅ docs/api/index.md"
  end

  private

  ##
  # Categorize a file path and extract class name.
  # Returns [type, name] or [nil, nil] if should be skipped.
  #
  def categorize_file(relative_path)
    # Compute category from actual class resolution, not hardcoded patterns
    class_name = compute_class_name_from_path(relative_path)
    return [ nil, nil ] unless class_name

    # Resolve actual class to determine type
    klass = begin
      class_name.constantize
    rescue
      nil
    end

    return [ nil, nil ] unless klass

    # Compute type from actual class hierarchy
    type = compute_component_type_from_class(klass)
    [ type, class_name ]
  end

  def compute_class_name_from_path(relative_path)
    # Compute class name from file path structure
    return nil unless relative_path.end_with?(".md")

    path_without_ext = relative_path.sub(/\.md$/, "")
    parts = path_without_ext.split("/")

    # Handle different directory structures
    case parts.first
    when "controllers"
      basename = parts.last
      basename.gsub("_controller", "").camelize + "Controller"
    when "models"
      parts[1..-1].map(&:camelize).join("::")
    when "services", "jobs", "mailers"
      parts.last.camelize
    when "concerns"
      parts[1..-1].map(&:camelize).join("::")
    else
      # Try to infer from path structure
      parts.map(&:camelize).join("::")
    end
  end

  def compute_component_type_from_class(klass)
    # Compute type from actual class hierarchy and methods
    return :model if klass.is_a?(Class) && klass < ActiveRecord::Base
    return :controller if klass.is_a?(Class) && klass < ActionController::Base
    return :mailer if klass.is_a?(Class) && klass < ActionMailer::Base
    return :job if klass.is_a?(Class) && klass < ActiveJob::Base

    # Check for service pattern
    if klass.is_a?(Class) && klass.instance_methods(false).any? { |m| [ :perform, :execute, :call ].include?(m) }
      return :service
    end

    # Default to concern for modules
    :concern
  end

  def generate_core_capabilities
    # Compute capabilities from actual model features and concerns
    capabilities = compute_capabilities_from_models
    capabilities.map { |c| "- #{c}" }.join("\n")
  end

  def compute_capabilities_from_models
    capabilities = []

    # Analyze models to determine capabilities
    models = ActiveRecord::Base.descendants.reject { |m| m.name == "ApplicationRecord" }

    # Compute capabilities from actual model structure (RailsAdmin-style)
    # Compute capabilities from model metadata (RailsAdmin-style)
    # Group models by domain patterns discovered from associations and columns
    models.each do |model|
      # Compute asset management from model structure
      if model.reflect_on_association(:children) || model.reflect_on_association(:parent)
        asset_features = []
        asset_features << "Hierarchical structures" if model.reflect_on_association(:children)
        asset_features << "Type-specific attributes" if model.reflect_on_association(:asset_type)
        asset_features << "JSON import/export" if model.included_modules.any? { |m| m.name&.include?("JsonImport") || m.name&.include?("JsonExport") }
        if asset_features.any? && !capabilities.any? { |c| c.include?("Asset Management") }
          capabilities << "**Asset Management** - #{asset_features.join(', ')}"
        end
      end

      # Compute rule engine from model structure
      if model.column_names.include?("schedule") || model.reflect_on_association(:rule_executions)
        rule_features = []
        rule_features << "Schedule-based execution" if model.column_names.include?("schedule")
        rule_features << "Attribute-based execution" if model.included_modules.any? { |m| m.name&.include?("Rule") && m.name&.include?("Execution") }
        if rule_features.any? && !capabilities.any? { |c| c.include?("Rule Engine") }
          capabilities << "**Rule Engine** - #{rule_features.join(' and ')}"
        end
      end

      # Compute data analytics from model structure
      if model.column_names.include?("timestamp") && model.reflect_on_association(:asset)
        analytics_features = []
        analytics_features << "Time-series collection" if model.column_names.include?("timestamp")
        analytics_features << "Aggregation functions" if model.included_modules.any? { |m| m.name&.include?("Analytics") }
        if analytics_features.any? && !capabilities.any? { |c| c.include?("Data Analytics") }
          capabilities << "**Data Analytics** - #{analytics_features.join(', ')}"
        end
      end

      # Compute notifications from model structure
      if model.column_names.include?("severity") || model.column_names.include?("message")
        if !capabilities.any? { |c| c.include?("Notifications") }
          capabilities << "**Notifications** - Multi-severity alerts and notifications"
        end
      end

      # Compute user management from model structure
      if model.column_names.include?("email") || model.reflect_on_association(:roles)
        user_features = []
        user_features << "Authentication" if model.included_modules.any? { |m| m.name&.include?("Confirmable") || m.name&.include?("Recoverable") }
        user_features << "Authorization" if model.reflect_on_association(:roles)
        user_features << "Role-based access control" if model.included_modules.any? { |m| m.name&.include?("Ability") }
        if user_features.any? && !capabilities.any? { |c| c.include?("User Management") }
          capabilities << "**User Management** - #{user_features.join(', ')}"
        end
      end
    end

    capabilities
  end

  def concerns_with_feature?(feature_name)
    find_concerns_with_interactions.any? do |concern|
      concern.enables_interactions.any? { |i| i[:type].to_s.include?(feature_name.to_s) }
    end
  end

  def generate_interactions_summary
    concerns = find_concerns_with_interactions
    interactions = concerns.flat_map { |c| c.enables_interactions }

    summary = interactions.map do |interaction|
      models = interaction[:models].join(" ↔ ")
      "- **#{interaction[:type].to_s.humanize}**: #{models} (#{interaction[:description]})"
    end.uniq.first(10).join("\n")

    summary || "No interactions declared yet."
  end

  def generate_models_summary
    models = ActiveRecord::Base.descendants.reject { |m| m.name == "ApplicationRecord" }

    models.map do |model|
      features_count = model.respond_to?(:features) ? model.features.count : 0
      "- **#{model.name}** - #{features_count} feature#{'s' if features_count != 1} declared"
    end.join("\n")
  end

  def generate_concerns_summary
    concerns = find_concerns_with_interactions

    concerns.map do |concern|
      interactions_count = concern.enables_interactions.count
      "- **#{concern.name}** - Enables #{interactions_count} interaction#{'s' if interactions_count != 1}"
    end.join("\n")
  end

  def generate_models_list
    models = ActiveRecord::Base.descendants.reject { |m| m.name == "ApplicationRecord" }

    models.map do |model|
      features = model.respond_to?(:features) ? model.features : []
      validations = features.select { |f| f[:type] == :validates }.count
      associations = features.select { |f| f[:type] == :associates }.count
      methods = features.select { |f| f[:type] == :provides }.sum { |f| f[:args].count }
      scopes = features.select { |f| f[:type] == :scopes }.sum { |f| f[:args].count }

      <<~MODEL
        #### #{model.name}

        - Validations: #{validations}
        - Associations: #{associations}
        - Methods: #{methods}
        - Scopes: #{scopes}
      MODEL
    end.join("\n")
  end

  def generate_concerns_list
    concerns = find_concerns_with_interactions

    concerns.map do |concern|
      interactions = concern.enables_interactions.map do |i|
        "- #{i[:type]}: #{i[:models].join(', ')}"
      end.join("\n")

      <<~CONCERN
        #### #{concern.name}

        #{interactions}
      CONCERN
    end.join("\n")
  end

  def find_concerns_with_interactions
    ObjectSpace.each_object(Module).select do |mod|
      next false unless mod.is_a?(Module)
      next false if mod.name.nil? || mod.name.empty?
      next false if mod.name.start_with?("Rails::") || mod.name.start_with?("ActiveRecord::") || mod.name.start_with?("Action")
      mod.respond_to?(:enables_interactions) && mod.enables_interactions.any?
    end
  end
end
