# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

# Exclude node_modules and other generated directories
AllCops:
  Exclude:
    - 'docs/node_modules/**/*'
    - 'node_modules/**/*'
